### ISSUE TITLE
Add resource download 

### ISSUE THREAD

**Issue by dhakadv06** [K-E-N-W-A-Y/Skillshare-DL#1]
Can you please add resource download folder as well

https://www.skillshare.com/classes/How-to-design-prototype-a-Mobile-UIUX-Design-Experience-using-Figma-design-tool-Learn-Figma/2017505298/projects

below the resources, we have the files

**Comment by K-E-N-W-A-Y** [comment]
sorry i don't have time to figure anyway to do this
