### ISSUE TITLE
Hey @K-E-N-W-A-Y, - Colab site is NOT WORKING!  Please help.

### ISSUE THREAD

**Issue by besscella** [K-E-N-W-A-Y/Skillshare-DL#10]
Hey @K-E-N-W-A-Y,

The **Colab site** for downloading Skillshare courses, has **stopped working** again.  I keep getting the Traceback error...

Traceback (most recent call last):
  File "/root/.Skillshare-DL/dl.py", line 16, in <module>
    main()
  File "/root/.Skillshare-DL/dl.py", line 11, in main
    dl.download_course_by_url(course_url)
  File "/root/.Skillshare-DL/skillshare.py", line 32, in download_course_by_url
    self.download_course_by_class_id(m.group(1))
  File "/root/.Skillshare-DL/skillshare.py", line 74, in download_course_by_class_id
    raise Exception('Failed to read video ID from data')
Exception: Failed to read video ID from data

**Any chance you could fix this please?**

Thank you in advance.

_Originally posted by @besscella in https://github.com/K-E-N-W-A-Y/Skillshare-DL/issues/5#issuecomment-734378535_

**Comment by ANASABDIALI** [comment]
me to i also have that problem

**Comment by Iulipartenie** [comment]
Don't worry, K-E-N-W-A-Y always fixed it.

**Comment by calvinhobbes23** [comment]
Issue resolved! Enjoy People. Thanks to @asadraihan1 for an account.

https://colab.research.google.com/github/calvinhobbes23/Skillshare-DL/blob/master/Skillshare_DL_%5BKENWAY%5D.ipynb

**Comment by besscella** [comment]
Thanks a million!  You're an absolute Legend.  👍😁

**Comment by Iulipartenie** [comment]
Thank you very much! Appreciate it!

**Comment by ANASABDIALI** [comment]
thank you bro i realy appreciate you
GREAT LOVE FROM SOMALIA

**Comment by K-E-N-W-A-Y** [comment]
sorry for the late reply, nice work @calvinhobbes23 thanks for the keeping project alive. i don't have live skillshare account anymore. so if anyone having problems please use @calvinhobbes23 [fork repo](https://colab.research.google.com/github/calvinhobbes23/Skillshare-DL/blob/master/Skillshare_DL_%5BKENWAY%5D.ipynb)
