### ISSUE TITLE
Resources Downloader

### ISSUE THREAD

**Issue by Rei-dz** [K-E-N-W-A-Y/Skillshare-DL#11]
**Add resources downloader separated from course downloader.**

![image](https://user-images.githubusercontent.com/76688811/103213946-23aed500-494a-11eb-9209-404434424da8.png)

**Comment by Rei-dz** [comment]
I just saw from closed issues that you don't have time for this, thank you anyways.

**Comment by 04anubhavv** [comment]
@K-E-N-W-A-Y I have highly modified script for downloading, which can even download a video in diff resolution  + subs + resources. but I made that for pyqt5 if you have a time you can convert it to CLI based script? 

if yes, I will happy to add you to my private repo
