### ISSUE TITLE
Ressources donwload

### ISSUE THREAD

**Issue by val3riefr** [K-E-N-W-A-Y/Skillshare-DL#12]
Hi, the downloader works, however how can we get the ressources files?

**Comment by K-E-N-W-A-Y** [comment]
duplicate of #11

**Comment by ANASABDIALI** [comment]
Thanks you 100%
Many students like me are greeting you from Somalia 🇸🇴♥️.
I really appreciate your for the great work you have done.
I don't know what to say .
Thank thanks
