### ISSUE TITLE
not connecting to G drive via auth code showing Error on startup

### ISSUE THREAD

**Issue by mqasidk** [K-E-N-W-A-Y/Skillshare-DL#4]
ValueError                                Traceback (most recent call last)
<ipython-input-2-697923b34052> in <module>()
      1 #@markdown <h3>⬅ Run This Cell to  Mount Gdrive
      2 from google.colab import drive
----> 3 drive.mount('/content/drive')

/usr/local/lib/python3.6/dist-packages/google/colab/drive.py in mount(mountpoint, force_remount, timeout_ms, use_metadata_server)
    247       wrote_to_fifo = True
    248     elif case == 5:
--> 249       raise ValueError('mount failed: invalid oauth code')
    250   if not wrote_to_fifo:
    251     with open(fifo, 'w') as fifo_file:

ValueError: mount failed: invalid oauth code

**Comment by K-E-N-W-A-Y** [comment]
are you sure your auth code is correct?

**Comment by mqasidk** [comment]
first of all thanks for the instant replay! yes, I checked so many times & also use the incognito window the confirm this issue but rapidly it's showing the same error.

**Comment by K-E-N-W-A-Y** [comment]
i tried & every time it works without any errors. i can't reproduce this error. you can use rclone to copy or move your files to gdrive

![image](https://user-images.githubusercontent.com/25846872/92355770-90376700-f102-11ea-9dad-f59204f67d3b.png)

**Comment by mqasidk** [comment]
yes, I found that problem I just remove the old access from g drive & do re-access them as a fresh connect & it's work fine but now I think your account expires can you please update the script or if it's possible in work for future?
