### ISSUE TITLE
Subtitles & Course Resources?

### ISSUE THREAD

**Issue by erny94** [K-E-N-W-A-Y/Skillshare-DL#8]
Hi there,
Thanks for the [fix](https://github.com/calvinhobbes23/Skillshare-DL) for both Developers, the downloader is really awesome and helpfully but it could be more if improved to be able to load Subtitles & Course Resources

**Comment by K-E-N-W-A-Y** [comment]
sorry for the late reply, i don't have free time to work on these projects (busy IRL). hope someone will pickup & improve this
